### ISSUE TITLE
Opaque attributes

### ISSUE THREAD

**Issue by sergiobelotti** [italobusi/actn-wdm-pluggable-modelling#13]
https://github.com/italobusi/actn-wdm-pluggable-modelling/blob/b25297c8c8df2618074da848da322556755b91dd/draft-rokui-ccamp-actn-wdm-pluggable-modelling.md?plain=1#L440

Opaque attributes have still to be discussed and agreed. I've open a specific issue for that.
The related section in the proposed version of the draft should be deleted here, and copied/pasted into this issue

**Comment by reza-github** [comment]
I've raised the following issue for addressing the need for coherent pluggable opaque attributes.

https://github.com/italobusi/actn-wdm-pluggable-modelling/issues/14#issue-2740643907

Closing the issue as DUPLICATE of above issue
